# Generated by Django 6.0.5 on 2026-05-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rent_amount', models.PositiveIntegerField(verbose_name='Montant du loyer')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Début du contrat')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Fin du contrat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property', verbose_name='Logement')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['name'],
            },
        ),
    ]
