# Generated by Django 6.0.5 on 2026-05-05 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(verbose_name='Mois concerné')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('certified', 'Certifiée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('certified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de certification')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Fichier PDF')),
                ('sent_to_tenant', models.BooleanField(default=False, verbose_name='Envoyé au locataire')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('cost_in_credits', models.PositiveIntegerField(default=0, verbose_name='Coût en crédits')),
                ('was_free', models.BooleanField(default=False, verbose_name='Était gratuit')),
                ('free_reason', models.CharField(blank=True, max_length=50, verbose_name='Raison de la gratuité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tenants.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-month'],
                'unique_together': {('tenant', 'month')},
            },
        ),
    ]
