# Generated by Django 6.0.5 on 2026-05-05 19:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('currency', models.CharField(choices=[('XOF', "Franc CFA (XOF) - Sénégal, Côte d'Ivoire, Bénin, Togo, Burkina, Mali, Niger"), ('XAF', 'Franc CFA (XAF) - Cameroun, Gabon, Congo, RCA, Tchad'), ('GNF', 'Franc Guinéen (GNF) - Guinée')], default='XOF', max_length=3, verbose_name='Devise')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('subscription_type', models.CharField(choices=[('free_trial', 'Essai gratuit (1er mois)'), ('pay_per_use', 'Pay-per-use (100 FCFA/chambre)'), ('subscription', 'Abonnement mensuel')], default='free_trial', max_length=20, verbose_name="Type d'abonnement")),
                ('credits_balance', models.IntegerField(default=0, verbose_name='Crédits disponibles')),
                ('subscription_active', models.BooleanField(default=False, verbose_name='Abonnement actif')),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Début abonnement')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin abonnement')),
                ('subscription_tier', models.CharField(blank=True, max_length=20, verbose_name='Tranche abonnement')),
                ('first_month_free_used', models.BooleanField(default=False, verbose_name='1er mois gratuit utilisé')),
                ('consecutive_paid_months', models.IntegerField(default=0, verbose_name='Mois payés consécutifs')),
                ('free_month_used', models.BooleanField(default=False, verbose_name='Mois offert utilisé')),
                ('first_year_complete', models.BooleanField(default=False, verbose_name='1ère année terminée')),
                ('free_trial_usage', models.IntegerField(default=0, verbose_name='Quittances utilisées pendant essai')),
                ('total_rooms_declared', models.IntegerField(default=0, verbose_name='Total chambres déclarées')),
                ('last_compliance_check', models.DateTimeField(blank=True, null=True, verbose_name='Dernier contrôle conformité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
