# Generated by Django 6.0.5 on 2026-05-05 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonnement mensuel'), ('credits', 'Achat de crédits'), ('free_month', 'Mois offert (promo)'), ('first_month_free', 'Premier mois gratuit (bienvenue)')], max_length=30, verbose_name='Type de paiement')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('simulation', 'Simulation (développement)')], max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('credits_purchased', models.PositiveIntegerField(default=0, verbose_name='Crédits achetés')),
                ('month_concerned', models.DateField(blank=True, null=True, verbose_name='Mois concerné')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
